language: node_js
node_js:
  - 14.6.0

cache:
  yarn: true
  directories:
    - node_modules
    
install:
  - npm install -g lerna
  - npm install -g yarn
  - npm run bootstrap

script:
  - yarn test
before_deploy:
  - yarn tsc

deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master

env:
  global:
    secure: kmxGMhRG0QGml1UkOeUFD4ib4yaN3lNO1nGH7Fbnbd1JAabD8+x61Acv3hmb3lN/eNedJGj3DtS2IIG/UPS0trHWJ8oTN5a04pGuKwx0jtTSq4ULlHJK8NJTSDHoNqi5iJxtZqUYWb5uXKvgtAN+g8cSpPmRUINxzCnZ+wISOCmr0vwShs6SXlRuaw2iekiGFTf1OYRLkEQmdSPG39P8atwiGo+PvIM5TaKgCLicBTx05gSVxjOnUiAAypnbElTJNcp/QlClgFa9QY/n1Ph7wVf8gQtqTR5KCt/rTVz5OQZblY/oqSWi7vaFZfS2qfAKJ0FbzTZcfP5f2cTGfIpMhLIfFWhTCW4lWFUkX8XkvSbhuymTDzBzwUKlJPZa//T+HbeZwckVoo56WuUBODAfrE/GDHnVmEG9uA7TWfBTkpgHEzGSyzaISdN+ziAYn/W4rLX5CBSrzkO60okGOi4uVBHdz9pyOHEKhjcfZJBaMyZt2POiRUcnqtQsf4zGkANvQu2UvSe4uSi8uArh/xRq5d3TWCKE2raLwHGjd+Tou2VFFn/oLlKfB3U1EidESPEBARubbDu6vGbB8d94IeyZsWz9sXrUFQN3175Ik7hiS3/VI4q5OtHfLVatxJmAmKO8klO1KCxxOipmarpaqNYo6iQ7ImvoBJDXeYMDvHIdnvU=
