name: deploy-production
on:
  push:
    branches: [ master ]
    commit-ignore:
      - 🚀
      - [bot]
      - Update from Shopify
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          npm i -g yarn
          yarn
          yarn build
          yarn lerna version patch --conventional-commits --yes --exact --create-release github
          git remote add -t ${GITHUB_REF} github "https://$GITHUB_ACTOR:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config user.email "info@processcreative.com.au"
          git config user.name "Process-Admin"
          git add package.json
          git commit -m "🚀 Increased Semvar"
          git push github HEAD:${GITHUB_REF}
          echo "registry=https://npm.pkg.github.com/@process-creative" >> .npmrc
          echo "@process-creative:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
          yarn lerna publish from-package --yes --registry //npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}