name: deploy-production
on:
  push:
    branches: [ no-jquery ]
    commit-ignore:
      - 🚀
      - [bot]
      - Update from Shopify
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "@process-creative:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc

          npm install
          npm install -g yarn
          yarn lerna version patch --conventional-commits --yes --exact --create-release github
          
          git remote add github "https://$GITHUB_ACTOR:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config user.email "info@processcreative.com.au"
          git config user.name "Process-Admin"
          git add --all
          git commit -m "🚀 Increased Semvar"
          git push github HEAD:${{ env.GITHUB_REF }}
          
          yarn lerna publish from-package --yes --registry //npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}