name: deploy-production
on:
  push:
    branches: [ master ]
    commit-ignore:
      - 🚀
      - [bot]
      - Update from Shopify
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          git config --global user.email "info@processcreative.com.au"
          git config --global user.name "Process-Admin"

          npm i -g lerna
          npm i -g yarn

          yarn bootstrap
          yarn tsc
          yarn binlink
          yarn lerna version patch --conventional-commits --yes --exact --create-release github

          git remote set-url origin "https://$GITHUB_ACTOR:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git add --all
          git commit -m "🚀 Increased Semvar" || echo "Nothing to commit"
          git push
          echo "registry=https://npm.pkg.github.com/@process-creative" >> .npmrc
          echo "@process-creative:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GH_TOKEN}" >> .npmrc

          yarn lerna publish from-package --yes --registry //npm.pkg.github.com
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}